name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'shadanan' }}
    permissions:
      contents: write
      id-token: write
    environment:
      name: mediar-release
    steps:
      - &app
        id: app
        uses: actions/create-github-app-token@v2.2.1
        with:
          app-id: 1855004
          private-key: ${{ secrets.RELEASER_PRIVATE_KEY }}
      - &checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - &install-rust
        uses: moonrepo/setup-rust@v1
        with:
          components: clippy,rustfmt
      - uses: release-plz/action@v0.5.125
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ steps.app.outputs.token }}

  pr:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'shadanan' }}
    permissions:
      contents: write
      pull-requests: write
    environment:
      name: mediar-release
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - *app
      - *checkout
      - *install-rust
      - uses: release-plz/action@v0.5.125
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ steps.app.outputs.token }}
